site_name: Jellybot
site_url: https://introvrt-lounge.github.io/jellybot/
repo_url: https://github.com/introVRt-Lounge/jellybot
repo_name: introVRt-Lounge/jellybot

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: amber

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Commands: commands.md
  - Limits: limits.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
